### ISSUE TITLE
Model Definition Language

### ISSUE THREAD

**Issue by imhele** [act-auth/modeldl#1]
> 1.0.0-draft

## 概述

Model Definition Language (ModelDL) 是一种定义语言，旨在提供简洁、灵活、统一的模型定义语法描述数据完整性约束。

例如，此 ModelDL 声明了一个名为 `Account` 的模型：

```yaml
Account:
  id[int]: null
  name[str]:
    max: 32
```

`Account` 模型包含整型的 `id` 属性与字符串类型的 `name` 属性，其中 `id` 没有额外的约束条件，`name` 的额外约束条件为长度不超过 32 。

ModelDL 不是一种能进行计算的编程语言，而是一种专用于模型声明的语言。ModelDL 没有强制绑定的语言实现，而可以在任何图灵完备的编程语言中得到统一解释与功能映射。

### 源文本解析

为了降低学习成本与解释器开发难度， ModelDL 源文本遵循 [YAML 1.2 规范](https://yaml.org/spec/1.2/spec.html) 。ModelDL 源文本可直接使用 YAML 解析器进行源文本解析后送入 ModelDL 语法解释器。

> 以下内容中除特殊说明外，*YAML* 、 *YAML 规范* 、 *YAML 语法* 等 YAML 相关词语均指代 YAML 1.2 规范或其内容。

### 指代

在下文的规范说明中，`*()` 指代可选内容，`#()` 指代可重复集合。`{}` 与 `[]` 分别指代 YAML 中的 `Mapping` 与 `Sequence` 。例如：

```
( "abc" { "name" { "bob" } "friends" [ "alice" "jane" ] } )
```

以 YAML 规范化书写为：

```yaml
abc:
  name: bob
  friends:
    - alice
    - jane
```

### 转义

```
QuotedScalarsKey = ( "<" Scalar ">" AnyOtherSyntax )
Scalar = < YAML 规范所指的标量 >
```

ModelDL 文档中，除 YAML 规范内的转义规则外，映射目标（值）不涉及其他转义规则，映射源标量（键名）包含 ModelDL 语法表达式或关键词时，需要对映射源标量（键名）进行转义。例如，此 ModelDL 文档声明了两个模型，分别名为 `import` 与 `model[withPunctuator]` ：

```yaml
import:
  another-file.mdl: ImportedModel
<import>: @ImportedModel.oneOfAttributes
<model[withPunctuator]>:
  <anyAttr[withPunctuator>[str]: null
```

文档中第一个 `import` 为 Model 导入语法，从 `another-file.mdl` 中导入了名为 `ImportedModel` 模型；声明了 `import` 模型，引用自导入的 `ImportedModel` ；声明的 `model[withPunctuator]` 模型包含一个名为 `anyAttr[withPunctuator` 的字符串类型属性。

### Document

```
Document = { *( Imports ) *( DefaultExport ) #( Definition )  }
Definition = ModelDefinition | AttributeDefinition
```

ModelDL 文档主体部分为 `Definition` ，导入导出规则可选。

### Imports

```
Imports = ( "import" [ #( ModelDLFilePath { Import } ) ] )
ModelDLFilePath = AbsolutePath | RelativePath
AbsolutePath = < 绝对路径 >
RelativePath = < 相对当前的相对路径 >
Import = "*" | AsIdentity | ImportSpecificContent
AsIdentity = Scalar
ImportSpecificContent = [ #( ModelName | AttributeName | ImportAs ) ] | { #( ImportAs ) }
ImportAs = ( ( ModelName | AttributeName ) { AsIdentity } )
```

ModelDL 文档中可导入其他文件中定义的 `model` 或 `attribute` ，允许在当前文档中引用。导入分三类：

- 通配符 `"*"` 按原命名导入所有的 `model` 与 `attribute`
- `AsIdentity` 导入整份文档为特定标量
- `ImportSpecificContent` 导入文档中的指定内容

例如，从此文档中导入：

```yaml
Account:
  id[int]: null
  name[str]: null
email[str]:
  regexp: \S{1,}@[^\s\.]{1,}(?:\.[^\s\.]{1,}){1,}
```

导入规则为：

```yaml
import:
  - path-to-file.mdl: ImportedModel
  - path-to-file.mdl:
      - email: Email
      - Account
  - path-to-file.mdl:
      id: accountId
```

将导入 `ImportedModel` 、 `Email` 、 `Account` 、 `accountId` 四项内容。

### AttributeDefinition

```
AttributeDefinition = ( AttributeKey IntegrityConstraints )
AttributeKey = ( AttributeName TypeConstraint )
TypeConstraint = ( "[" #( TypeName ) "]" *( "?" ) )
TypeName = < ModelDL 默认支持与外部扩展的类型名 >
TypeNameSplitChar = "|"
```

例如

```yaml
birthday[date|null]?:
  default: null
```

### ModelDefinition

```
ModelDefinition = ( ModelKey { #( ModelDefinition | AttributeDefinition | DefaultExport ) } )
ModelKey = ModelName
```

例如

```yaml
Account:
  id[int]: null
  name[str]: null
  Friend:
    id[int]: null
    relationship[str]:
  friends[array]:
    items: @Friend.id
```

### DefaultExport

```
DefaultExport = ExportAttribute | ExportQuote
ExportAttribute = ( ( "default" TypeConstraint ) IntegrityConstraints )
ExportQuote = ( "default" { Quote } )
```

例如

```yaml
Account:
  id[int]: null
  name[str]: null
  default[object]:
    keys:
      id: @Account.id
      name: @Account.name
default: @Account
```

### IntegrityConstraints

```
IntegrityConstraints = IntegrityConstraintSet | IntegrityConstraintList
IntegrityConstraintSet = { #( IntegrityConstraint ) }
IntegrityConstraintList = [ #( IntegrityConstraint | IntegrityConstraintSet ) ]
IntegrityConstraint = ( ConstraintName ConstraintArgs )
ConstraintName = < ModelDL 默认支持与外部扩展的完整性约束名 >
ConstraintArgs = Collection | Scalar
Collection = < YAML 规范所指的集合 >
```

例如

```yaml
birthday[date|null]?:
  default: null
messages[array]:
  - ordered: hello
  - ordered: world
```

### Quote

```
Quote = ( "@" QuotePath )
QuotePath = #( ModelName | AttributeName )
QuotePathSplitChar = "."
```

例如

```
import:
  - account.mdl: Account
  - account.mdl:
      id: accountId
Team:
  teamId[int]: null
  member[int]: @Account.id # or `@accountId`
default: @Team
```

### Yaml

```yaml
Account:
  id[int]:
    min: 0
  name[str]:
    max: 64
  email[str]?:
    max: 128
    default: ""
  birthday[date|null]: null
  default[object]:
    keys:
      id: @Account.id
      name: @Account.name
      email: @Account.email
      birthday: @Account.birthday
    locale:
      zh-CN: 账户
      en-US: account # use key as fallback by default
default: @Account
```

### Convert to TypeScript

```ts
const Account = new validatorStatic.namespace({
  id: new validatorStatic.number('id').min(0).integer(true).required(),
  name: new validatorStatic.string('name').max(64).required(),
  email: new validatorStatic.string('email').max(128).default(''),
  birthday: new validatorStatic.alternatives('birthday')(new validatorStatic.date())(null),
}, definedTypes => {
  return new validatorStatic.object('Account')
    .keys({
      id: definedTypes.Account.id,
      name: definedTypes.Account.name,
      email: definedTypes.Account.email,
      birthday: definedTypes.Account.birthday,
    })
    .locale({
      'zh-CN': '账户',
      'en-US': 'account',
    });
});
```
